# Generated by Django 5.1.1 on 2024-09-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="service",
            new_name="services",
        ),
    ]
