# Generated by Django 5.1.1 on 2024-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0002_rename_service_order_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=70),
        ),
    ]
