# Generated by Django 5.1.1 on 2024-09-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0003_alter_customer_phone_number_alter_service_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tailor",
            options={"verbose_name": "Tailor"},
        ),
        migrations.AddField(
            model_name="order",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
