# Generated by Django 5.1.1 on 2024-09-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0004_alter_tailor_options_order_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="short_description",
            field=models.CharField(max_length=250),
        ),
    ]
