# Generated by Django 5.1.1 on 2024-09-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0005_order_is_paid_alter_order_short_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-is_active", "start_date")},
        ),
    ]
